version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-compose-db
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: compose-db
    volumes:
      - ./mysql-data:/var/lib/mysql
